# Generated by Django 3.2.2 on 2021-05-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='fname',
            field=models.CharField(max_length=10),
        ),
    ]
