# Generated by Django 3.2.2 on 2021-05-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_signup_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
