# Generated by Django 3.2.2 on 2021-05-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_signup_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='dob',
            field=models.DateField(default=10),
        ),
    ]
