# Generated by Django 3.2.2 on 2021-05-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_signup_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='dob',
            field=models.DateField(max_length=10),
        ),
    ]
